# Generated by Django 3.1.4 on 2021-01-12 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projeto',
            old_name='dataInicio',
            new_name='data_inicio',
        ),
        migrations.RenameField(
            model_name='projeto',
            old_name='dataTermino',
            new_name='data_termino',
        ),
        migrations.RenameField(
            model_name='projeto',
            old_name='retornoEsperado',
            new_name='retorno_esperado',
        ),
    ]
