# Generated by Django 3.1.5 on 2021-01-21 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210112_2015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='retorno_esperado',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='tipo',
        ),
    ]
